---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-namespaces
  annotations:
    policies.kyverno.io/title: Require Namespace for PipelineRun
    policies.kyverno.io/category: Tekton
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: PipelineRun
    kyverno.io/kyverno-version: 1.7.2
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >- 
      A Namespace is required for a PipelineRun
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-pipeline
    match:
      resources:
        kinds:
        - PipelineRun
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    validate:
      message: "A namespace is required"
      pattern:
        metadata:
          namespace: "!default"

